# CMS SETTINGS
backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)

# Add the workflow tab
# publish_mode: editorial_workflow

# Display a link to the live site
site_url: https://mhox1.net
display_url: MHOX

# Replace the logo on the login page
# logo_url: https://your-site.com/images/logo.svg

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Adds a search bar for collections
search: true

##############
# COLLECTIONS
##############
collections:
  # https://decapcms.org/docs/collection-types/
  #
  # BLOG
  # ______________ ________________
  # ___  __ )__  / __  __ \_  ____/
  # __  __  |_  /  _  / / /  / __
  # _  /_/ /_  /___/ /_/ // /_/ /
  # /_____/ /_____/\____/ \____/
  #
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Author Url",
          name: "authorurl",
          widget: "string",
          required: false,
        }
      - {
          label: "Featured Article",
          name: "featuredArticle",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Image Alt Text",
          name: "featuredImageAltText",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  #
  #  PAGES
  # ______________ _______ _____________
  # ___  __ \  __ `/_  __ `/  _ \_  ___/
  # __  /_/ / /_/ /_  /_/ //  __/(__  )
  # _  .___/\__,_/ _\__, / \___//____/
  # /_/            /____/
  #
  - label: "Pages"
    name: "Pages"
    files:
      # ABOUT PAGE
      - label: "About Page"
        name: "about"
        file: "/content/about.md"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: Title, name: title, widget: string }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
      # EXPERIENCE PAGE
      - label: "Experience"
        name: "experience"
        file: "/content/experience.md"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: Title, name: title, widget: string }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
